### ISSUE TITLE
Add codersrank portfolio

### ISSUE THREAD

**Issue by JakubAndrysek** [JakubAndrysek/Kubaandrysek.cz#31]
```html
      <script src="https://unpkg.com/@codersrank/work-experience@0.9.8/codersrank-work-experience.min.js"></script>
      <script src="https://unpkg.com/@codersrank/skills-chart@0.9.21/codersrank-skills-chart.min.js"></script>
      <script src="https://unpkg.com/@codersrank/portfolio@0.9.10/codersrank-portfolio.min.js"></script>
```

```html
                </div>
                {% endif %}
                {% endfor %}
        </div>
        {% endif %}

        <div class="card">
            <h1>Work experience</h1>
            <codersrank-work-experience username="jakubandrysek" branding="false" logos="true" ></codersrank-work-experience>
        </div>

        <div class="card ">
            <h1>Portfolio</h1>
            <codersrank-portfolio username="jakubandrysek" branding="false" logos></codersrank-portfolio>
        </div>

    </div>
</div>
```

```css
codersrank-timeline {
    --tooltip-text-color: #ffffff;
    --tooltip-bg-color: #444;
    --timeline-item-bg-color: #414b73;
    --tooltip-logo-size: 100px;
}

codersrank-portfolio {
    --logo-size: 15%;
    --logo-margin: 20px;
}
```
